### ISSUE TITLE
Blue Force Tracking seems to be broken.

### ISSUE THREAD

**Issue by nibbles-** [acemod/ACE3#1957]
ACE3 Version: 3.2.0

Mods:

@cba_a3
@ace3

Placed ACE3 Modules:
Blue Force Tracking

Description:
Blue force tracking does not work

Steps to reproduce:
Create a new mission in the MP editor and place a player and the BFT module and set it to Enabled.
No tracking icon is shown at player location

**Comment by nibbles-** [comment]
22:38:13 Attempt to override final function - bis_functions_list
22:38:13 Attempt to override final function - bis_functions_listpreinit
22:38:13 Attempt to override final function - bis_functions_listpostinit
22:38:13 Attempt to override final function - bis_functions_listrecompile
22:38:13 Attempt to override final function - bis_fnc_missiontaskslocal
22:38:13 Attempt to override final function - bis_fnc_missionconversationslocal
22:38:13 Attempt to override final function - bis_fnc_missionflow
22:38:13 [21561,174.313,0,"XEH: PreInit Started. v1.1.23.150604. MISSINIT: missionName=Test, worldName=VR, isMultiplayer=true, isServer=true, isDedicated=false"]
22:38:17 [21561,178.238,0,"XEH: PreInit Finished. CACHE DISABLED? (Disable caching with cba_cache_disable.pbo): SLX_XEH_RECOMPILE=false, CBA_COMPILE_RECOMPILE=false, CBA_FUNC_RECOMPILE=false"]
22:38:22 c:\w\stable\futura\lib\network\networkserver.cpp NetworkServer::OnClientStateChanged:NOT IMPLEMENTED - briefing!
22:38:22 [21574,183.08,0,"XEH: PostInit Started"]
22:38:22 [21574,183.125,0,"CBA_VERSIONING: cba=1.1.23.150604, ace=3.2.0.0, "]
22:38:22 [ACE]: ACE is version 3.2.0.0.
22:38:22 [ACE] Extension version: ace_break_line: 3.2.0-bf4e95e
22:38:22 [ACE] Extension version: ace_parse_imagepath: 3.2.0-bf4e95e
22:38:22 [ACE] Extension version: ace_clipboard: 3.2.0-bf4e95e
22:38:22 [ACE] Extension version: ace_fcs: 3.2.0-bf4e95e
22:38:22 [ACE] Extension version: ace_advanced_ballistics: 3.2.0-bf4e95e
22:38:22 [21574,183.653,0,"XEH: PostInit Finished. State: _isClient=true, _isJip=false, _isDedClient=false, _isServer=true, _isDedServer=false, _playerCheckDone=true, _sp=false, _startInitDone=true, _postInitDone=true, _mpRespawn=false, _machineType=1, _sessionId=1, _level=0, _timeOut=false, _game=3, BIS_functions=<NULL-object>, group=<NULL-group>, player=B Alpha 1-1:1 (nibbles), _playerType="B_Soldier_F", _playerGroup=B Alpha 1-1"]
22:38:22 [ACE] Settings received from server
22:38:22 [ACE] Settings initialized
22:38:22 "[ACE] JIP Medical init for player"
22:38:22 [ACE]: Blue Force Tracking Module initialized.
22:38:23 Warning: no idc entry inside class RscDisplayServerGetReady/objects/Compass 
22:38:42 SimulWeather - Cloud Renderer - noise texture file is not specified!
22:38:43 Deinitialized shape [Class: "B_Soldier_F"; Shape: "a3\characters_f\blufor\b_soldier_01.p3d";]
22:38:43 c:\w\stable\futura\lib\network\networkserver.cpp ClearNetServer:NOT IMPLEMENTED - briefing!
22:38:43 Extensions:
22:38:43   ace_clipboard (F:\Steam\steamapps\common\arma 3\@ace3\ace_clipboard.dll) [3.2.0.0] [3.2.0.0]

22:38:43   ace_fcs (F:\Steam\steamapps\common\arma 3\@ace3\ace_fcs.dll) [3.2.0.0] [3.2.0.0]

22:38:43   ace_advanced_ballistics (F:\Steam\steamapps\common\arma 3\@ace3\ace_advanced_ballistics.dll) [3.2.0.0] [3.2.0.0]

22:38:43   ace_medical (F:\Steam\steamapps\common\arma 3\@ace3\ace_medical.dll) [3.2.0.0] [3.2.0.0]

22:38:43   ace_parse_imagepath (F:\Steam\steamapps\common\arma 3\@ace3\ace_parse_imagepath.dll) [3.2.0.0] [3.2.0.0]

22:38:43   ace_break_line (F:\Steam\steamapps\common\arma 3\@ace3\ace_break_line.dll) [3.2.0.0] [3.2.0.0]

**Comment by Glowbal** [comment]
Fix merged in with #1968

**Comment by Dumedo** [comment]
Still not working for me on 3.3.1
place module 
bft enable yes
interval 1
hide AI yes

place 2 or more group with Teamleader
In editor preview I can see other group markers and myself in map as TL of my group.
In dedicated server with other players I can't see any makers.

**Comment by bux578** [comment]
@Dumedo Thank you for your report. Could you please create a new issue and follow this guideline: http://ace3mod.com/wiki/user/how-to-report-an-issue.html
