### ISSUE TITLE
getHitpoints function doesn't support reflector hitpoints

### ISSUE THREAD

**Issue by SzwedzikPL** [acemod/ACE3#2259]
During tests of https://github.com/acemod/ACE3/pull/2230 i noticed that after dragging or carrying lamp reflectors are always working (event if damaged before).

The reason is that this dont support reflector hitpoints (or selections? only `getHit` return anything)

https://github.com/acemod/ACE3/blob/master/addons/common/functions/fnc_fixFloating.sqf#L24

**Comment by commy2** [comment]
I'll investigate. Doubt those can be manipulated with `setHitPointDamage` and `getHitPointDamage` though.

**Comment by jonpas** [comment]
@commy2 look at #2279

**Comment by SzwedzikPL** [comment]
@commy2 i've prepared https://github.com/acemod/ACE3/pull/2279 but have problem with `setdamage`.

**Comment by commy2** [comment]
I advice that you use the new
`getAllHitPointsDamage cursorTarget`
command

**Comment by commy2** [comment]
@SzwedzikPL
What about:
`[cursorTarget] call ace_common_fnc_getReflectorsWithSelections`
?

**Comment by SzwedzikPL** [comment]
The problem is not that `getHitpoints` doesn't support reflectors, after dragging some object (i.e. lamp with reflectors) we'r calling:
https://github.com/acemod/ACE3/blob/master/addons/dragging/functions/fnc_dropObject.sqf#L60
And in fixFloating fnc we do not support reflectors, so thats why reflectors are always working after drag/carry.

**Comment by commy2** [comment]
k. I understand now.

I'll see that I fix this after 3.2.2. Currently cleaning up (== incorperating new commands...) all the other stuff with hitpoints.

https://github.com/acemod/ACE3/pull/2319

**Comment by SzwedzikPL** [comment]
@commy2 ok. Should I close https://github.com/acemod/ACE3/pull/2279 ?

**Comment by commy2** [comment]
Nah. Leave it open for now.

**Comment by commy2** [comment]
Fixed in  #2601. Sry for this taking a month. Had other priorities even though this ended up being really simple.

**Comment by SzwedzikPL** [comment]
This is not fixed. Please test it with https://github.com/acemod/ACE3/pull/2230

1. Place `Portable Lights (double)` from `Objects (construction)`
2. Shot to one of the reflectors
3. Carry lamp
4. Place lamp

You'll see that after placing both reflectors are working.

**Comment by PabstMirror** [comment]
`allowDamage false` from fixCollision blocks adding damage from `setHitIndex`
biki says "The command does not prevent object from taking scripted damage such as setDamage or setHit. "

Can reproduce with this code having no effect: 
```
qq1 allowDamage false;
qq1 setHitIndex [0,1];
```

**Comment by commy2** [comment]
Pabst, you are my hero again!

**Comment by commy2** [comment]
And a big FU you to you BI.

**Comment by commy2** [comment]
Wiki is wrong. The same happens with:
`cursorTarget allowDamage !false; cursorTarget setHit ["light_1_hitpoint", 1]`

**Comment by PabstMirror** [comment]
Can we swap order of the events?
Or do we need to look into a proper "allowDamage" handler so we can disable and then reenable?

**Comment by commy2** [comment]
We can not swap the order of these commands. We will need a proper allowDamage function like forceWalk etc.

**Comment by commy2** [comment]
https://github.com/acemod/ACE3/issues/2757

**Comment by jonpas** [comment]
> Wiki is wrong. The same happens with:

Edit the BIKI! :grin:

**Comment by commy2** [comment]
Edited it. Also added that allowDamage false soldiers can still drown. (R.I.P. Ghost)

**Comment by jonpas** [comment]
I still see
> The command does not prevent object from taking scripted damage by setDamage. It does prevent damage from setHit and setHitIndex. 

I see the new drown note though.

**Comment by commy2** [comment]
Oh, I forgot to edit the
https://community.bistudio.com/wiki/allowDammage
page.
Only edited
https://community.bistudio.com/wiki/allowDamage

**Comment by bux578** [comment]
`00:53, 17 October 2015‎ Killzone Kid (Talk | contribs)‎ . . (2,350 bytes) (-72)‎ . . (Undo revision 92470 by Commy2 (talk) no effect on sethit)`

**Comment by commy2** [comment]
Well fuck the wiki then.

**Comment by jonpas** [comment]
Well that's... A bit sad I shall say...

**Comment by SzwedzikPL** [comment]
https://github.com/acemod/ACE3/pull/3163 solved problem. Thank you @PabstMirror
