### ISSUE TITLE
FixFloating Error

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#2621]
ACE3 Version: 3.3.2.0 f77242fce33240f9f367d0bdb8be40b9a4cf84c6 (latest master)

The below error pops up when releasing a carried or dragged object of specific type - in this case a chair, for example `Land_CampingChair_V2_F`, happens with other chairs as well. Apparently it's because they don't have hitpoints.
```
2:00:48 Error in expression <arams ["_array", "_code"];


_array = + _array;

{
_array set [_forEachIndex, _x>
 2:00:48   Error position: <_array;

{
_array set [_forEachIndex, _x>
 2:00:48   Error foreach: Undefined variable in expression: _array
 2:00:48 File z\ace\addons\common\functions\fnc_map.sqf, line 7
 2:00:48 Error in expression <n_fnc_getHitpoints;
_hitPointDamages = [_hitPoints, {_object getHitPointDamage _>
 2:00:48   Error position: <_hitPoints, {_object getHitPointDamage _>
 2:00:48   Error Undefined variable in expression: _hitpoints
 2:00:48 File z\ace\addons\common\functions\fnc_fixFloating.sqf, line 14
```

**Comment by jonpas** [comment]
Invalid, I was actually not on latest master, damn you Git :banana:

**Comment by PabstMirror** [comment]
Drag/carry doesn't seem to be enabled for those chairs, should it?

**Comment by jonpas** [comment]
No, but I was adding it for #2620 , if there are objections, write it there of course. :)

**Comment by PabstMirror** [comment]
Excellent, was just checking because I didn't see them.

**Comment by commy2** [comment]
This is not fixed in master. It is however fixed in #2598.

Commit: https://github.com/acemod/ACE3/commit/1de3343092b91c297e3de30c128abafb6b736fd7#diff-9bb10d0be40dd380ce136f7f6a480058R24

It was introduced when I replaced the stuff in `FUNC(getHitpoints) with `getAllHitpointDamages`.

`getAllHitpointDamages` is supposed to return an array containing 3 arrays:
`[[<HITPOINTS>],[<SELECTIONS>,[<DAMGE_VALUES>]]`,
but when used on an object without any hitpoints it simply returns `[]` instead of `[[],[],[]]`, which I consider as a bug personally.

Btw.
https://community.bistudio.com/wiki/getAllHitPointsDamage
claims that the return value is a number.

**Comment by jonpas** [comment]
Well, I am not getting the error after I merged master into my branch (and realised I am behind before that), so it must have been something in master that fixed that particular case.

**Comment by commy2** [comment]
Oh yes. NVM, fixed that particular case in #2601. Root cause isn't fixed though. At least in master.
