### ISSUE TITLE
A-10D - GuidedBombUnit-12

### ISSUE THREAD

**Issue by madpat3** [acemod/ACE3#2784]
ACE3 Version: 3.3.2 
(stable)

Mods:
@CBA_A3
@ace

Placed ACE3 Modules:
none

Description:
With A-10D's GBU-12 Bombs, you can't lock onto lasered targets.

Steps to reproduce:
-Place a Blufor A-10D as player on map. 
-Place a Blufor Darter Drone (flying) on map. 
-Place a UAV terminal on map next to the plane (i know its more comfortable to put the terminal into player's init-line, but i don't know how, so fxxx it). 

Nevertheless, 

-preview the mission, get out the plane, grab the terminal, get in the plane, again. open terminal and get control over the drone.
-disable autonominous behavior and get in as gunner. 
-lase a target.
-close the terminal an lift-off the plane.
-head towards the lased position, having GBU-12's armed and try to lock on target... you can't.

Where did the issue occur?
"Editor"

RTP log file:
http://pastebin.com/SNdEDq7N

**Comment by PabstMirror** [comment]
Ref PR #2560

In 3.2.2 locking was disabled on a base class `RocketPods`, which broke a lot of vanilla weapons that should be able to lock.

It is fixed on master and will be included in next release.

Right now an temp fix would be to remove missleGuidace, javelin, laser and laser_selfDesignate pbos.

**Comment by madpat3** [comment]
It is fixed on master and will be included in next release.

will the laser be totally renewed so we can see it in on infrared like we did in arma2?

**Comment by KantiOM** [comment]
Still not working. Even though I see laser on radar, I can't lock on it. And if I launch GBUs, they not locking in freefall (like it was in Arma 2 Ace2). Also AGM/DAGR not locking aswell. So what the point in laser code if nothing locking on it?

**Comment by madpat3** [comment]
testet in Editor(sp). works for gbu.
regarding agm, it depends on the Version of maverics. only E and L can lock onto lasers. others are camera guided, similar to the javeline or minispike. so i suppose its not the E/L version. 
dagr - not testet.

**Comment by KantiOM** [comment]
I don't how you tested it, but it don't work for me. https://youtu.be/UD4e7NVTNOw

**Comment by madpat3** [comment]
did the same as you, except for put the darter drone on map in the Editor. height 200, flying.
preview. connect to darter, set off autonomous behavior, lase. 
maybe it's a bug with the drone in the backpack, for you saw a bug with the remote laserdesignator, too.
