### ISSUE TITLE
Auto switch to Binocular

### ISSUE THREAD

**Issue by Neodyn** [acemod/ACE3#2916]
ACE3 Version: 3.4.0

Mods:
@CBA_A3
@ace

Description:
If you have an Binocular or a Rangefinder in intended slot and exit an car from driverseat the player auto switch to the Binocular or a Rangefinder.

Steps to reproduce:
- Place a Tank or Car
- Take a Binocular or a Rangefinder with you
- get in the car
- get out of the car

**Comment by rebelvg** [comment]
Yep, can confirm.

**Comment by PabstMirror** [comment]
`[_unit] call FUNC(binocularMagazine)` is called from ace_common_fnc_getAllGear on each frame.

That `selectWeapon` the binocs and then attempts to switch back, but the _muzzle and _mode are from the car `TruckHorn2` so it fails.

I don't think we should be running all that code each frame, maybe we can use `weaponsItems`.

**Comment by commy2** [comment]
Fix will be done later today.

**Comment by PabstMirror** [comment]
Fixed by #2935

**Comment by OnkelDisMaster** [comment]
Sorry, that I ask about a fixed thing, but I´ve tested #2957 again with the current master. It still doesn´t seem to work.

**Comment by PabstMirror** [comment]
Fixes are on branch `release`
https://github.com/acemod/ACE3/tree/release

**Comment by OnkelDisMaster** [comment]
Oh, ok thanks and nevermind!
