### ISSUE TITLE
Javelin Issue / Question

### ISSUE THREAD

**Issue by rebelvg** [acemod/ACE3#3937]
**Arma 3 Version:** `1.60` (stable)
**CBA Version:** `2.4.1` (stable)
**ACE3 Version:** `3.5.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Javelin rocket falls down after launch. https://www.youtube.com/watch?v=rSjNWqRjdZk
I discussed this with someone on slack but he couldn't reproduce.

**Steps to reproduce:**
- Get Javelin AT.
- Aim, launch.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None.

**RPT log file:**
RPT.
https://gist.github.com/rebelvg/e8ae43c43bbf535a4aca59d17e377d89
Mission file from video.
https://gist.github.com/rebelvg/7f1a444369e20516e4dfd595ccbb7724

**Comment by BaerMitUmlaut** [comment]
I couldn't replicate this. Can somebody else?

**Comment by DLEGION** [comment]
javelin / titan lock tanks but AT rockets are going...boh! surely not on target tanks !
ace version 3.6.2

**Comment by LevelPulse** [comment]
ETA on fix?

**Comment by commy2** [comment]
when it's done

**Comment by PabstMirror** [comment]
We think it has been already been fixed on master with #4130
I will do some testing tomorrow.

**Comment by rebelvg** [comment]
I tested this on a latest master and couldn't even fire a Javelin for some reason. Using the mission file I added to the issue.

**Comment by DLEGION** [comment]
hello !
i noticed the other thread about javelin bug has been closed....has it been merged with this ?
or solved?
thanks for the infos.....i'm still trying to solve this problem for my dedicated server ! 
thanks !

**Comment by commy2** [comment]
which one? We can't merge issues on github, but they can get linked by referencing them.

**Comment by bux578** [comment]
#4204

**Comment by DLEGION** [comment]
...the problem with the javelin right now is that is unreliable...sometimes the missile goes down on the locked tank, sometimes fly straight up !

**Comment by LevelPulse** [comment]
100% failure rate for me.

**Comment by Walterros** [comment]
Had multiple successful Titan launches tonight, then for no apparent reason they stopped working once again with missiles flying off in every direction.

**Comment by esteldunedain** [comment]
People, I'm sorry to tell you that if you are not using the latest source your reports may be outdated. There was a sepparate bug with the Javelin that was fixed three days ago #4204.

**Comment by rebelvg** [comment]
I tested this after that commit and it didn't fix it for me.

**Comment by rebelvg** [comment]
Okay, I have to add that I tested just now on the latest master and it worked. Strange, it didn't work after that commit.

**Comment by DLEGION** [comment]
sorry for my ignorance...how get/use latest "source" ?

**Comment by commy2** [comment]
Install git bash and type:
`git clone https://github.com/acemod`

You then have to also compile it.
http://ace3mod.com/wiki/development/setting-up-the-development-environment.html

**Comment by DLEGION** [comment]
ook thanks i will try :)

**Comment by Walterros** [comment]
Pulled the latest source and compiled it, tested in a single player editor mission. I'm able to hit RHS BTRs, but doesn't hit RHS T72s or BMPs.

**Comment by DLEGION** [comment]
i still have to check with latest version, but i noticed locking problems with aircrafts too.
 some tanks seems unloakable for AG missiles !

**Comment by commy2** [comment]
Can someone confirm that the T72 and BMP cannot be locked on even with RHS weapons? E.g. Aircraft ATG missiles?

**Comment by DLEGION** [comment]
will try to check tonight when i get home. if someone can share directly the related .PBos would be easier and faster for me set up everything and test ( i formatted recently, and must re-do all the procedure to enable tools ecc...)
thanks !

**Comment by Walterros** [comment]
The individual I had compile the source code sent me the wrong files. After verifying that I had the actual code, the appear to be working on all RHS vehicles. So, fixed from my end.

**Comment by DLEGION** [comment]
can you please upload and share the .PBOs ? huge thanks !

**Comment by DLEGION** [comment]
hi all!
tested the master, and can confirm everything seems to work fine! all tanks hit ! will do more tests tomorrow, but i think its fixed!
yeah, good job!
