### ISSUE TITLE
Javelin can't attack Tanks

### ISSUE THREAD

**Issue by ZeusWrath** [acemod/ACE3#4204]
**Arma 3 Version:** 1.62 (stable)
**CBA Version:** 3.0.0.160713 (stable)
**ACE3 Version:** 3.6.2 (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
Javelin(Titan Launcher), can't  attack only Tanks. The missile fly above target in the unknown direction/
The problem with the other targets was not seen.

**Steps to reproduce:**
Place in the editor, player as Missile specialist. (I was the NATO men) 
Place in the editor, any tanks (!only tank) T-100, Leopard, Merkava
Shoot into this tank

**Where did the issue occur?**
Editor (Singleplayer)

**Placed Modules:**
--

**RPT log file:**
--

**Comment by freghar** [comment]
I can confirm this, has been happening at least since v1.60, for Titan variants as well. It seems that the missile just flies straight without any locking, regardless of firing mode (TOP/DIR).

It isn't 100% reproducible though - it seems to happen only when the target is in front of some obstacle (building, cliff with rocks, etc.). No idea why.

**Comment by esteldunedain** [comment]
Might be related to `cursorObject` bugging out. I observed some evidence of strange behaviour the other day while playing around in Apex.

**Comment by DLEGION** [comment]
i can confirm its bugged for me too.

**Comment by Bobblehead1** [comment]
I can confirm as well. But I doesn't only occur while the target is behind some kind of cover. I tested in the editor and it also happens when the target is on an open field. I planted a tank 1,5km away from me and got lock-on and everything, but the missile aims for the Orbit. The only times where I could repeatedly hit the target, was while it was moving. (You can try this as well if you like) Up until now I could not find a solution to this. I guess I somehow have to work around it until someone comes up with a plan.

**Comment by esteldunedain** [comment]
Could you save a very simple mission in which this happens and upload it
somewhere?

**Comment by Bobblehead1** [comment]
hmm...where could I upload it ?

**Comment by bux578** [comment]
Dropbox / Google Drive ?

**Comment by esteldunedain** [comment]
Yeah, or mega.nz

**Comment by Bobblehead1** [comment]
Ok, I'm at it

**Comment by Bobblehead1** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=738083495

How about this ?

**Comment by esteldunedain** [comment]
Perfect, thank you

**Comment by Bobblehead1** [comment]
Anything new ?

**Comment by esteldunedain** [comment]
@Bobblehead1, I couldn't yet replicate the bug in your mission. I fired at the different targets with the default top attack mode and indeed the missile goes way up...but it then comes down and hits the target as expected.

Are you sure the bug happens consistently in that mission you uploaded?

**Comment by Bobblehead1** [comment]
It did with me. I sometimes hit a standing target. But that's like a 1 in 5. Or even less. The only target I could hit consistently was the moving tanks.

**Comment by esteldunedain** [comment]
Sorry, I still couldn't replicate it. Are you experiencing low fps or something like that?

**Comment by Bobblehead1** [comment]
nothing....I really don't know what this is all about. Getting desperate here.

**Comment by jonpas** [comment]
Can you upload full RPT @Bobblehead1 ?

**Comment by Bobblehead1** [comment]
I'm new here and basically just signed up for this issue so please forgive me but, what do you mean by that ?

**Comment by jonpas** [comment]
https://community.bistudio.com/wiki/Crash_Files#Arma_3

**Comment by Bobblehead1** [comment]
https://drive.google.com/folderview?id=0B-MqkwqS-06GQXBwUUw5LVhXZHc&usp=sharing

**Comment by DLEGION** [comment]
just as side note....i have the same problem and use CBA 3.0.0  and ACE3 3.6.2
thanks guys !

**Comment by freghar** [comment]
Reproducer on
https://drive.google.com/open?id=0B-VJDqVv2ipPVXBuZkltYzBlcHc

Multiple tanks placed, Titan AT used to reduce the variables in play (no Arsenal) as it has the same bug as the Javelin. I'm able to lock onto any of the tanks, but when I fire the missile, it goes "straight", unguided. In the case of the nearest tank, it even hits the buildings further downrange.

I also placed one tank on which the missile works (commented in Eden), as a control.

Default release of ACE v3.6.2 used, no pbo changes. The RPT log doesn't have anything interesting, just usual info stuff which is there on any game/mission start.

**Comment by DLEGION** [comment]
its like some not moving tanks are like "not really locked on" by the titan.
moving targets usually get correctly hit by topdown attack.

**Comment by byannoni** [comment]
I also have this issue in 3.6.0 and 3.6.2. For me, it is reproducible every time in the editor, local server, and dedicated server. The missile just goes off into the horizon in top-down or direct mode regardless of whether or not the vehicle is moving. It works fine on unmanned vehicles, though. In addition to tanks, I experience this issue with at least the Tempest.

@DLEGION, I'm not an expert on this, but try removing ACE_Javelin and ACE_missileguidance on your dedicated server as well. I have had issues connecting to my dedicated server if I didn't have the exact same ACE pbo files in place on both the client and the server.

**Comment by DLEGION** [comment]
hi! 
thanks byannoni for the reply ! well ...what you say works, the problem is compatibility...as i saied i tried but other people (that have standard ACE3 ) cannot join !
any ideas ?
thanks

**Comment by PabstMirror** [comment]
Fixed by #4130

**Comment by ZeusWrath** [comment]
Why is this ticket closed? The problem is not solved! 
I expect more than a month when my javelin can shoot into a tank! But this is still not happening(
**The missile flies up always! flying behind the horizon**

**Comment by jonpas** [comment]
It has been fixed by #4130 as @PabstMirror specified and it is tagged for *3.7.0*, which is not yet released.
