### ISSUE TITLE
SPAR series can't use ACE Magazines

### ISSUE THREAD

**Issue by ColonelCarston** [acemod/ACE3#4207]
**Arma 3 Version:** `1.62` stable
**CBA Version:** `3.0.0` stable
**ACE3 Version:** `3.6.2` stable

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- The SPAR series of rifles are unable to use any magazines added in by ACE.

**Steps to reproduce:**
1.Enter the Virtual Arsenal
2.Select a SPAR rifle
3.Unable to add ACE Magazines

1.Enter the editor
2.Add a soldier with a SPAR rifle and ACE Magazines
3.Unable to load ACE Magazines into rifle

**Where did the issue occur?**
- Editor (Singleplayer) / Virtual Arsenal

**Placed Modules:**
- None

**RPT log file:**
http://pastebin.com/FQGpzCA5

**Comment by jonpas** [comment]
Fixed by #4329

**Comment by ColonelCarston** [comment]
If I'm reading the commit correctly, this issue isn't fully fixed. This bug applies to the entire SPAR series, so the SPAR 17 still needs to be fixed as well.

**Comment by jonpas** [comment]
It has been added to the base class, as far as I know the other SPAR weapons inherit from that one and should therefore have ACE magazine compatibility as well.

**Comment by ColonelCarston** [comment]
According to the commit, only 5.56 NATO magazines were added. The SPAR 17 fires 7.62 NATO, and thus it needs to have its own magazines whitelisted.

**Comment by commy2** [comment]
@PabstMirror  ^ ?

**Comment by Glowbal** [comment]
#4340

**Comment by PabstMirror** [comment]
@ColonelCarston - thank you for checking the work, I forgot there was a 7.62 varient.

**Comment by ColonelCarston** [comment]
@PabstMirror No problem! Thanks for the fixes!
