### ISSUE TITLE
Script error in map gestures

### ISSUE THREAD

**Issue by Cuel** [acemod/ACE3#4522]
**Arma 3 Version:** Stable
**CBA Version:** Latest stable
**ACE3 Version:** 3.7.0

**Description:**
Alt+m1 click on the map screen produces a script error

```
_key in (_hash select 1); 
>
12:42:01   Error position: <select 1); 
>
12:42:01   Error Zero divisor
12:42:01 File x\cba\addons\hashes\fnc_hashHasKey.sqf, line 11
12:42:01 Error in expression <gestures_defaultColor};
};

_mapHandle drawIcon ["\a3\ui_f\data\gui\cfg\Hints\i>
12:42:01   Error position: <drawIcon ["\a3\ui_f\data\gui\cfg\Hints\i>
12:42:01   Error 0 elements provided, 4 expected
12:42:01 File z\ace\addons\map_gestures\functions\fnc_drawMapGestures.sqf, line 42
12:42:01 Error in expression <], []], [[]]], "_key"];
```

**Where did the issue occur?**
- Local

**Comment by Glowbal** [comment]
Is this fixed by #4486?

**Comment by commy2** [comment]
I think so. Apparently this is also covered by https://github.com/acemod/ACE3/issues/4477

**Comment by Cuel** [comment]
Still getting this.
[ACE] (common) INFO: ACE is version 3.8.1.11.
[ACE] (common) INFO: CBA is version 3.1.1.161012 (min required 3.1.1)

**Comment by commy2** [comment]
Yes... Milestone is 3.8. *2* ; )

**Comment by Cuel** [comment]
durp, nvm then
