### ISSUE TITLE
Extension Ace_cfs.dll or Ace_advance ballistics.dll error (Fixed)

### ISSUE THREAD

**Issue by Akouafortes** [acemod/ACE3#5019]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
-  I get  Ace_cfs.dll or Ace_advance ballistics.dll error and ends the scenario.

**Steps to reproduce:**
- When im on editor and choose the mission even in multiplayer i get  Ace_cfs.dll or Ace_advance ballistics.dll error and ends the scenario.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- any troops

**RPT log file:**
http://www.filehosting.org/file/details/651322/arma3_x64_2017-03-22_20-00-05.rpt

**Comment by PabstMirror** [comment]
```
Advanced Combat Environment 3.9.0 |                @ACE3 |      false |             GAME DIR | cee51a00e11f5ab1b513d99ee82977dc3bd5e83a |   4d3f436 | C:\Users\Λεωνίδας\Documents\Arma 3\@ACE3
```
We just released 3.9.1 yesterday
The dlls are the same, but it might be worth trying to update

We had seen issues with the dlls not loading with last release when using x64
You might want to try x32

**Comment by Akouafortes** [comment]
I've install 3.9.1 and i have still the same issue even with x32 versrion having only ace3 and cba. I have no antivirus and i have put an exception those folders at window defender in case something block the dll's.

**Comment by Akouafortes** [comment]
Nevermind i fixed it... i moved all my addons in an External Hard Drive, i think my dll's blocked from my ssd which i have windows.
