### ISSUE TITLE
Ace does not function whatsoever

### ISSUE THREAD

**Issue by Thrunix** [acemod/ACE3#7053]
**Arma 3 Version:** `1.94` (stable / rc / dev)
**CBA Version:** `3.11.2` (stable / dev + commit hash)
**ACE3 Version:** `3.12.6` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
-Ace interaction menu will not appear in any circumstance, be it self interaction, interaction with others, or interaction with objects/ 

**Steps to reproduce:**
load up arma 3 and play on any server involving ACE.

**Where did the issue occur?**
-everywhere m8

**Additional information:**
- issue persists through re downloading of ACE through steam and otherwise, deletion of profiles, re downloading of Arma3 entirely, deletion of all profile folders and re downloading of Arma 3 afterwords. 

ace debug
-https://pastebin.com/URVEWXuB

RPT file
https://pastebin.com/zahy1PCt

**Comment by bux** [comment]
Fill out the issue template. Versions and the RPT file is missing.

**Comment by Thrunix** [comment]
fixed both

**Comment by bux** [comment]
That is still not the RPT file but rather just the ACE debug output.
And you're using an outdated ACE3 version. We're already at **v3.12.6**
 https://github.com/acemod/ACE3/releases/tag/v3.12.6

**Comment by commy2** [comment]
3.9 was released 28 months ago. Proably time to update...

**Comment by Thrunix** [comment]
fixed both for real this time. Sorry for the trouble, new to fiddling with this kinda stuff
